### ISSUE TITLE
POST data to CGI-script does not receive EO

### ISSUE THREAD

**Issue by kriztioan** [civetweb/civetweb#296]
When sending POST-data to a CGI-script, EOF is not received through STDIN because the write end of the pipe is not closed by the child process after forking [and before replacing the process image with that of the CGI-script]. In other words, read keeps blocking in the CGI-script. Note that the read end in the parent is properly closed. A straightforward fix is to have spawn_process in civetweb.c receive the fdin [and other file-descriptors] as the pipe-array[s]:

`spawn_process(struct mg_connection *conn,
              const char *prog,
              char *envblk,
              char *envp[],
              int fdin[2],
              int fdout[2],
              int fderr[2],
              const char *dir)`

The child then simply closes fdin[1], fdout[0] and fderr[0]; in essence both ends of fdin, fdout and fderr are closed, as the read, write and write ends are duplicated to STDIN, STDOUT and STDERR of the child process, respectively.

`(void)close(fdin[0]);
 (void)close(fdout[1]);
 (void)close(fderr[1]);
 (void)close(fdin[1]);
 (void)close(fdout[0]);
 (void)close(fderr[0]); `

handle_cgi_request` then calls spawn_process as:

`pid = spawn_process(conn, p, blk.buf, blk.var, fdin, fdout, fderr, dir);`

I am using the civetweb under Mac/OSX as an embedded web server.

**Comment by bel2125** [comment]
Are you sure?
Actually [here](https://github.com/civetweb/civetweb/blob/master/src/civetweb.c#L7448) we have a `fclose(in);` to make sure the child CGI script gets the EOF. The fdin[1] is associated with the `FILE * in` by calling  `in = fdopen(fdin[1], "wb")` before (see [http://pubs.opengroup.org/onlinepubs/009695399/functions/fdopen.html](fdopen), [http://pubs.opengroup.org/onlinepubs/009695399/functions/fclose.html](fclose): *"The fclose() function shall perform the equivalent of a close() on the file descriptor that is associated with the stream pointed to by stream."*). So there is a `close` for `fdin[1]`.

Are you using the latest version from this repository or an older release?

Is there an issue (a blocking script, ...) that can be reproduced easily?
Can you give some steps to reproduce this problem?

Unfortunately I do not have an OSX system for testing, but I guess it should not be any different from a Linux system in this respect.

**Comment by kriztioan** [comment]
I am sure :-)
The issue is not that EOF is not sent, it is not received because the write end of the STDIN-pipe is not closed by the forked child process.

Quoted from, for example, http://tldp.org/LDP/lpg/node11.html :
"If the parent wants to receive data from the child, it should close fd1, and the child should close fd0. If the parent wants to send data to the child, it should close fd0, and the child should close fd1. Since descriptors are shared between the parent and child, we should always be sure to close the end of pipe we aren't concerned with. **On a technical note, the EOF will never be returned if the unnecessary ends of the pipe are not explicitly closed.**"

I am using the latest version of civetweb from the repository. Currently nowhere in the code is the write-end of the STDIN-pipe closed by the child. Mac OX is BSD-based, so it should not behave differently from any other Linux system.

Find attached a straightforward example HTML-page and C-code. The HTML-page simple posts a text field named 'test' to the compiled C-code, which will simple output the raw form-data, e.g., 'test=blah'. The C-code reads until EOF because of the while-statement (read returns '0' on receiving EOF - see read manpage). You will need to update the action-attribute of the HTML-form to point to your server and to whatever you named the compiled C-code.

[test_read.zip](https://github.com/civetweb/civetweb/files/222425/test_read.zip)

**Comment by bel2125** [comment]
I added a test case: https://github.com/civetweb/civetweb/blob/master/test/cgi_test.c
I can reproduce the behavior if I do not read `CONTENT_LENGTH` bytes (like I always did before), but just read until there is an error.
I can reproduce it in Windows as well as in Linux (I don't have a Mac/OSX system). So it seems to be a platform independent issue. In Windows, there is no `fork`, so you can not execute anything written in the source code file of the parent in the process context of the child process (like `childpid = fork(); if (childpid==0) {/* Close up standard input of the child */ close(0); exec(...);}` in Linux).

Did you already create a fix? Where *precisely* do you think the handles have to be closed?

**Comment by kriztioan** [comment]
I don't think reading EOF should be necessarily considered an "error"; it simply states that you got all there is. In the case that is not the amount of data there should be, i.e., the pipe was closed before all data was sent, it is an error.

I came across the issue because I was reading the POST-data from C++ using std::string::getline in a while-loop, which won't break until EOF is received.

I don't know how things are done in Windows, so unfortunately I can be of no help there.

I have implemented a fix in my copy of the code. The unnecessary handles need to be closed after duplicating the file handles to STDIN, STDOUT and STDERR using dup2 in the newly forked child process and before the current process image is replaced by the CGI-script using the execle-call.

Find attached a .diff with the current master [04/18/2016].
[civetweb.c.diff.zip](https://github.com/civetweb/civetweb/files/224759/civetweb.c.diff.zip)

**Comment by bel2125** [comment]
I applied your patch for Linux, and I'm trying to create an equivalent for Windows.

After the patch, the Linux code looks like:
```
			/* Keep stderr and stdout in two different pipes.
			 * Stdout will be sent back to the client,
			 * stderr should go into a server error log. */
			(void)close(fdin);
			(void)close(fdout);
			(void)close(fderr);

			/* Close write end fdin and read end fdout and fderr */
			(void)close(fdin[1]);
			(void)close(fdout[0]);
			(void)close(fderr[0]);
```
this probably has to be 
```
			/* Keep stderr and stdout in two different pipes.
			 * Stdout will be sent back to the client,
			 * stderr should go into a server error log. */
			(void)close(fdin[0]);
			(void)close(fdout[1]);
			(void)close(fderr[1]);

			/* Close write end fdin and read end fdout and fderr */
			(void)close(fdin[1]);
			(void)close(fdout[0]);
			(void)close(fderr[0]);
```

**Comment by kriztioan** [comment]
Apologies, you are correct - I downloaded the latest version from master and reapplied my changes to be sure I was making the diff with the latest version of the civetweb.c; obviously I forgot something.

Sorry again I am no help with the Windows side of things.

**Comment by bel2125** [comment]
I think for Windows, the handles must be explicitly set to "do not inherit":

```
	/* Mark handles that should not be inherited. See
	 * https://msdn.microsoft.com/en-us/library/windows/desktop/ms682499%28v=vs.85%29.aspx
	 */
	SetHandleInformation((HANDLE)_get_osfhandle(fdin[1]),
	                     HANDLE_FLAG_INHERIT,
	                     0);
	SetHandleInformation((HANDLE)_get_osfhandle(fdout[0]),
	                     HANDLE_FLAG_INHERIT,
	                     0);
	SetHandleInformation((HANDLE)_get_osfhandle(fderr[0]),
	                     HANDLE_FLAG_INHERIT,
	                     0);
```

This seems to work in a first test.

Next I'm trying to get the test running on the Travis CI environment as well.

**Comment by bel2125** [comment]
> I've updated the .diff attached above for concurrently.

I already integrated your diff, and made some changes to get it compiling for Windows as well. So I can not apply a changed diff now.
Anyway, in a next step I have to test this more intensively.
Could you still have a look at the changes in the current CivetWeb code?

**Comment by kriztioan** [comment]
Thank you for taking my issue serious and for quickly resolving it.

The changes to the CivetWeb code look appropriate. I presume you successfully tested the changes with the added cgi_test.c/cgi_test.html combo added in the test-directory, i.e., the script is not blocking anymore.

It looks to me the Windows' philosophy regarding not having unnecessary ends of the pipes is the same as for Linux, although implemented differently - does Windows now also pass the cgi_test.c/cgi_test.html combo?

I also noticed a conceptional mistake in my initial test_read.c; I saw you worked around that in your implementation. I updated the the attached zip-archive above for concurrency. In any case, test_read.c/test_read.html works for me now.

I'll leave it up to you to close the issues as resolved :-)

**Comment by bel2125** [comment]
I tested it manually for Linux and Windows - I don't have OSX system available locally.
Before the fix, the cti_test blocked on both, afterwards it worked for Windows and Linux.

The cgi_test.cgi is already added to the Travis CI environment for Linux and OSX (https://travis-ci.org/civetweb/civetweb/builds/124314104), although I do not yet check the result of the POST request, so I don't know if the content is transferred correctly for OSX - but if it would be blocking, the test would have failed.
It is not yet added to Appveyor (the CI environment for Windows), since CGI handling works differently in windows anyway: For Windows an executable must be called '.exe'  - '.cgi' is not executable, while for Linux the file extension does not matter, only the 'x' flag. So the trick for windows is to create a `cgi_test.cgi` as a text file with one line `#!r:\cgi_test.exe` (or wherever the exe is located). It can be done, I just did not do it yet - but we don't need to track this in this issue.

So you confirmed it works for you now, thus I'm closing the issue.
